name: Deploy PDF

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/main.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: main
          path: out/main.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: joaoulian
          GIT_CONFIG_EMAIL: joaogabrielulian@gmail.com
